on:
  push:
    branches:
      -master




jobs:
  bulid:
    run-on: ubuntu-latest

    steps:
      - name: 'Printing folder contents'
        run: ls


      - uses: actions/chekout@v3

      - name: 'after'
        run: ls



